"""Convert the web app's next-intl messages into Flutter ARB files.

The Next.js app keeps its translations in
`kisan-dost/ventureHack/kisan-next/messages/{en,hi,gu,mr}.json` as nested
objects. Flutter's gen_l10n wants flat ARB files with `{placeholder}` metadata.

This script flattens the nested keys with underscores
(`Dashboard.healthStatus.healthy` -> `dashboard_healthStatus_healthy`), keeps
only the namespaces the mobile app actually uses, and writes the placeholder
metadata gen_l10n needs.

English is the template: a key missing from another locale is simply left out
of that locale's ARB, and Flutter falls back to English at runtime.

Usage (from the kisan_app directory):
    python tool/import_arb.py
"""

import io
import json
import os
import re

MESSAGES_DIR = os.path.join(
    "..", "kisan-dost", "ventureHack", "kisan-next", "messages"
)
OUT_DIR = os.path.join("lib", "l10n")
LOCALES = ["en", "hi", "gu", "mr"]

# Namespaces the mobile app uses. The marketing namespaces from the web landing
# page (Index, Hero, Footer, FarmingFeature, Services, HomeCropCare,
# TrustSection) are deliberately excluded.
NAMESPACES = [
    "Navigation",
    "Navbar",
    "Dashboard",
    "WeatherPage",
    "WeatherTips",
    "Products",
    "ProductsPage",
    "Communities",
    "ChatWidget",
    "myCrop",
    "Fertilizer",
    "DiseasesPage",
    "Crops",
    "YieldPredictor",
    "ProfitPredictor",
    "CropSuggestion",
]

PLACEHOLDER_RE = re.compile(r"\{(\w+)\}")

# Strings the mobile app needs that the web app never had — mostly offline and
# failure states, which a mobile client hits far more often than a browser on
# a desk. These are merged in after the import so re-running this script does
# not lose them. Add new app-only copy here, not by editing the ARB by hand.
APP_EXTRAS = {
    "en": {
        "profileEdit": "Edit profile",
        "profileSaved": "Saved",
        "productsTitle": "Products",
        "productsSearch": "Search products",
        "productsUsage": "How to use",
        "productsFeatures": "Why it helps",
        "productsPrice": "₹{amount}",
        "productsNone": "No products match that search",
        "productsStaticNote": "A reference list of common agri-inputs. Prices are indicative — check with your dealer.",
        "predTabMandi": "Mandi",
        "predTabYield": "Yield",
        "predTabProfit": "Profit",
        "predCrop": "Crop",
        "predArea": "Area (acres)",
        "predNdvi": "Crop greenness (NDVI)",
        "predNdviHelp": "How green and healthy the crop looks from above. Leave as-is if unsure.",
        "predSoilMoisture": "Soil moisture (%)",
        "predRainfall": "Season rainfall (mm)",
        "predFertCost": "Fertilizer cost (₹)",
        "predPestCost": "Pesticide cost (₹)",
        "predIrrigCost": "Irrigation cost (₹)",
        "predRun": "Estimate",
        "predRunning": "Working",
        "predYieldResult": "Expected harvest",
        "predTonnes": "{value} tonnes",
        "predPerAcre": "{value} t per acre",
        "predVsRegion": "Regional average {value} t per acre",
        "predAbove": "{value}% above your region",
        "predBelow": "{value}% below your region",
        "predRevenue": "Expected revenue",
        "predCosts": "Your input costs",
        "predMargin": "Left after input costs",
        "predMarginNote": "This counts only the fertilizer, pesticide and irrigation you entered. Seed, labour, land and transport are not included, so your real profit will be lower.",
        "predPrice": "₹{value} per quintal",
        "predConfidence": "{value}% confident",
        "predEstimatedPrice": "This estimate uses a baseline price, not a live market rate.",
        "predFallbackNote": "The prediction model could not be reached, so this is a rough estimate from average figures for this crop.",
        "advisoryTitle": "Crop calendar",
        "advisoryNoCrops": "Add a field and a crop, and this page will tell you what to do at each stage.",
        "advisoryNoneForCrop": "No stage guide for this crop yet.",
        "advisoryNothingDue": "Nothing is due right now. The next step is below.",
        "advisoryNow": "DO THIS NOW",
        "advisoryNextIn": "NEXT, IN {days} DAYS",
        "advisoryDone": "{count} earlier stages have passed",
        "advisoryDose": "{amount} for your plot",
        "advisoryGeneralNote": "A general guide by crop age, not an inspection of your field. Check the crop yourself before spraying, and follow the label on the pack.",
        "predQuintals": "{value} quintals",
        "predLoss": "You may not cover your input costs.",
        "schemesTitle": "Government schemes",
        "schemesSearch": "Search schemes",
        "schemesAll": "All",
        "schemesNone": "No schemes match that search",
        "schemesBenefits": "What you get",
        "schemesEligibility": "Who can apply",
        "schemesOpen": "Open official website",
        "schemesLaunched": "Started {when}",
        "schemesCuratedNote": "A hand-checked list, not a live government feed. Always confirm details on the official site.",
        "fertTitle": "Fertilizer calculator",
        "fertCrop": "Crop",
        "fertArea": "Area (acres)",
        "fertSoil": "Soil type",
        "fertSoilTest": "I have a soil test",
        "fertExistingN": "Nitrogen in soil (kg/acre)",
        "fertExistingP": "Phosphorus in soil (kg/acre)",
        "fertExistingK": "Potassium in soil (kg/acre)",
        "fertCalculate": "Calculate",
        "fertBuy": "What to buy",
        "fertUrea": "Urea",
        "fertDap": "DAP",
        "fertMop": "MOP",
        "fertKg": "{value} kg",
        "fertBags": "About {count} bags of 50 kg",
        "fertCost": "Roughly ₹{amount}",
        "fertCostNote": "An estimate from indicative shop prices, not a quote.",
        "fertReduced": "Your soil test reduced the dose — you need to buy less.",
        "fertSplitNote": "Apply nitrogen in 2–3 splits through the season, not all at sowing.",
        "onboardTitle": "Tell us about your farm",
        "onboardWhy": "This lets us give advice for your area and your crops.",
        "onboardName": "Your name",
        "onboardMobile": "Mobile number",
        "onboardVillage": "Village",
        "onboardDistrict": "District",
        "onboardMainCrop": "Main crop",
        "onboardFinish": "Continue",
        "onboardSkip": "Skip for now",
        "communityTitle": "Farmer community",
        "communityEmpty": "No posts yet",
        "communityHelpful": "Helpful",
        "communityComments": "{count} comments",
        "communityAsk": "Ask farmers",
        "communityPostTitle": "What is the problem?",
        "communityDetails": "Describe it",
        "communityCrop": "Crop",
        "communityPost": "Post",
        "communityPosting": "Posting",
        "communityAddComment": "Write a reply",
        "communitySend": "Send",
        "communityNoComments": "No replies yet. Be the first.",
        "communitySignInNote": "Sign in to reply or mark posts helpful.",
        "homeGreeting": "Namaste, {name}",
        "homeMyCrops": "My crops",
        "farmNoFields": "No fields yet",
        "farmNoFieldsHint": "Add your first field to get advice for your crops.",
        "farmAddField": "Add field",
        "farmAddCrop": "Add crop",
        "farmFieldName": "Field name",
        "farmArea": "Area",
        "farmVillage": "Village",
        "farmTaluka": "Taluka",
        "farmDistrict": "District",
        "farmState": "State",
        "farmSoilType": "Soil type",
        "farmIrrigation": "Irrigation",
        "farmWaterSource": "Water source",
        "farmFrequency": "Watering",
        "farmPreviousCrop": "Last crop",
        "farmCropName": "Crop",
        "farmVariety": "Variety",
        "farmSowingDate": "Sowing date",
        "farmCultivationMethod": "How was it sown",
        "farmNotes": "Notes",
        "farmStep": "Step {current} of {total}",
        "farmNext": "Next",
        "farmBack": "Back",
        "farmSave": "Save",
        "farmSaving": "Saving",
        "farmReview": "Check your answers",
        "farmDayCount": "Day {days}",
        "farmDelete": "Delete",
        "farmDeleteField": "Delete this field?",
        "farmDeleteFieldNote": "The crops in it will be removed too.",
        "farmCancel": "Cancel",
        "farmRequired": "Please fill this in",
        "farmBadNumber": "Enter a number",
        "farmUseLocation": "Use my location",
        "farmFields": "Fields",
        "farmCrops": "Crops",
        "farmNoCrops": "No crops in this field yet",
        "farmSaved": "Saved",
        "authTagline": "Your farming companion",
        "authGoogle": "Continue with Google",
        "authSigningIn": "Signing in",
        "authCancelled": "Sign-in was cancelled.",
        "authRejected": "Google could not sign you in. Please try again.",
        "authStateMismatch": "That sign-in link did not match. Please start again.",
        "authServerError": "We could not sign you in right now.",
        "authOffline": "You are offline. Connect and try again.",
        "authSignOut": "Sign out",
        "authProfile": "Profile",
        "authWhyGoogle": "We use your Google account so you never have to remember a password.",
        "mandiIndicative": "Indicative rate",
        "mandiIndicativeNote": "Real government data, but not a fresh reading from your local market today.",
        "weatherSearchHint": "Village, town or district",
        "weatherUseLocation": "Use my location",
        "weatherForecast": "Next days",
        "weatherLocating": "Finding your location",
        "weatherLocationDenied": "Location is off. Search for your village instead.",
        "weatherRain": "{value}% chance of rain",
        "weatherFeels": "Feels like {value}°",
        "weatherHumidity": "Humidity",
        "weatherWind": "Wind",
        "weatherSprayWarn": "Rain expected — do not spray today.",
        "weatherHeatWarn": "Very hot. Irrigate early morning or evening.",
        "weatherWindWarn": "Strong wind — spray will drift. Wait for calmer air.",
        "mandiTitle": "Mandi prices",
        "mandiCrop": "Crop",
        "mandiState": "State",
        "mandiPerQuintal": "per quintal",
        "mandiRange": "Range {min} – {max}",
        "mandiLive": "Live government rate",
        "mandiEstimate": "Estimated rate",
        "mandiEstimateNote": "No live market data for this crop here. This is a government baseline, not a traded price.",
        "mandiArrival": "Market date {date}",
        "mandiNotYourDistrict": "Nearest reporting market",
        "diagnoseUnclear": "The photo was not clear enough",
        "diagnoseHowToFix": "How to get a good photo",
        "diagnoseGuide": "Fill the frame with one affected leaf",
        "diagnoseTakePhoto": "Take photo",
        "diagnoseGallery": "Choose from gallery",
        "diagnoseCompressing": "Preparing photo",
        "diagnoseUploading": "Uploading",
        "diagnoseAnalysing": "Analysing leaf",
        "diagnoseMatching": "Finding treatments",
        "diagnoseSlowNote": "The first check of the day can take up to a minute.",
        "diagnoseHealthy": "Healthy",
        "diagnoseInfected": "Disease found",
        "diagnoseConfidence": "{value}% sure",
        "diagnoseWhatToDo": "What to do now",
        "diagnoseFarmingSteps": "Farming steps",
        "diagnoseSymptoms": "What to look for",
        "diagnoseCauses": "Why it happened",
        "diagnoseBuy": "Products to use",
        "diagnoseExpertNote": "Please confirm with an expert before you spray.",
        "diagnoseRetake": "Check another leaf",
        "diagnoseTooLarge": "That photo is too large. Please take a new one.",
        "diagnoseNoCamera": "Camera is not available on this device.",
        "diagnosePermission": "Allow camera access to check your crop.",
        "diagnoseKeepPhoto": "Your photo is saved. You can try again.",
        "appOffline": "You are offline. Showing saved information.",
        "appSlow": "This is taking longer than usual. Please wait.",
        "appError": "Something went wrong.",
        "appRetry": "Try again",
        "appLastUpdated": "Updated {time}",
        "appLanguage": "Language",
        "navDiagnose": "Diagnose",
        "navFarm": "My Farm",
        "navInsights": "Insights",
        "navMore": "More",
        "comingSoon": "Coming soon",
    },
    "hi": {
        "profileEdit": "प्रोफ़ाइल बदलें",
        "profileSaved": "सहेजा गया",
        "productsTitle": "उत्पाद",
        "productsSearch": "उत्पाद खोजें",
        "productsUsage": "कैसे इस्तेमाल करें",
        "productsFeatures": "क्यों फ़ायदेमंद है",
        "productsPrice": "₹{amount}",
        "productsNone": "इस खोज से कोई उत्पाद नहीं मिला",
        "productsStaticNote": "आम कृषि सामग्री की संदर्भ सूची। भाव अनुमानित हैं — अपने डीलर से पुष्टि करें।",
        "predTabMandi": "मंडी",
        "predTabYield": "उपज",
        "predTabProfit": "मुनाफ़ा",
        "predCrop": "फ़सल",
        "predArea": "क्षेत्रफल (एकड़)",
        "predNdvi": "फ़सल की हरियाली (NDVI)",
        "predNdviHelp": "ऊपर से फ़सल कितनी हरी और स्वस्थ दिखती है। पता न हो तो वैसे ही रहने दें।",
        "predSoilMoisture": "मिट्टी की नमी (%)",
        "predRainfall": "मौसम की बारिश (मि.मी.)",
        "predFertCost": "खाद का खर्च (₹)",
        "predPestCost": "दवा का खर्च (₹)",
        "predIrrigCost": "सिंचाई का खर्च (₹)",
        "predRun": "अनुमान लगाएँ",
        "predRunning": "गणना हो रही है",
        "predYieldResult": "अनुमानित पैदावार",
        "predTonnes": "{value} टन",
        "predPerAcre": "{value} टन प्रति एकड़",
        "predVsRegion": "क्षेत्रीय औसत {value} टन प्रति एकड़",
        "predAbove": "आपके क्षेत्र से {value}% ज़्यादा",
        "predBelow": "आपके क्षेत्र से {value}% कम",
        "predRevenue": "अनुमानित आमदनी",
        "predCosts": "आपका लागत खर्च",
        "predMargin": "लागत के बाद बचत",
        "predMarginNote": "इसमें सिर्फ़ आपकी डाली हुई खाद, दवा और सिंचाई गिनी है। बीज, मज़दूरी, ज़मीन और भाड़ा शामिल नहीं, इसलिए असली मुनाफ़ा कम होगा।",
        "predPrice": "₹{value} प्रति क्विंटल",
        "predConfidence": "{value}% निश्चित",
        "predEstimatedPrice": "यह अनुमान आधार भाव पर है, लाइव मंडी भाव पर नहीं।",
        "predFallbackNote": "पूर्वानुमान मॉडल तक पहुँच नहीं पाए, इसलिए यह इस फ़सल के औसत आँकड़ों से बना मोटा अनुमान है।",
        "advisoryTitle": "फ़सल कैलेंडर",
        "advisoryNoCrops": "खेत और फ़सल जोड़ें, फिर यह पन्ना हर चरण पर बताएगा कि क्या करना है।",
        "advisoryNoneForCrop": "इस फ़सल के लिए अभी चरण सूची नहीं है।",
        "advisoryNothingDue": "अभी कुछ करना नहीं है। अगला कदम नीचे है।",
        "advisoryNow": "अभी यह करें",
        "advisoryNextIn": "अगला, {days} दिन में",
        "advisoryDone": "{count} पिछले चरण बीत चुके हैं",
        "advisoryDose": "आपके खेत के लिए {amount}",
        "advisoryGeneralNote": "यह फ़सल की उम्र के हिसाब से सामान्य सलाह है, आपके खेत की जाँच नहीं। छिड़काव से पहले फ़सल खुद देखें और डिब्बे पर लिखा निर्देश मानें।",
        "predQuintals": "{value} क्विंटल",
        "predLoss": "हो सकता है लागत भी न निकले।",
        "schemesTitle": "सरकारी योजनाएँ",
        "schemesSearch": "योजना खोजें",
        "schemesAll": "सभी",
        "schemesNone": "इस खोज से कोई योजना नहीं मिली",
        "schemesBenefits": "क्या मिलेगा",
        "schemesEligibility": "कौन आवेदन कर सकता है",
        "schemesOpen": "आधिकारिक वेबसाइट खोलें",
        "schemesLaunched": "{when} में शुरू",
        "schemesCuratedNote": "यह जाँची हुई सूची है, सरकारी लाइव फ़ीड नहीं। जानकारी आधिकारिक साइट पर ज़रूर देखें।",
        "fertTitle": "खाद कैलकुलेटर",
        "fertCrop": "फ़सल",
        "fertArea": "क्षेत्रफल (एकड़)",
        "fertSoil": "मिट्टी का प्रकार",
        "fertSoilTest": "मेरे पास मिट्टी जाँच है",
        "fertExistingN": "मिट्टी में नाइट्रोजन (कि.ग्रा./एकड़)",
        "fertExistingP": "मिट्टी में फॉस्फोरस (कि.ग्रा./एकड़)",
        "fertExistingK": "मिट्टी में पोटाश (कि.ग्रा./एकड़)",
        "fertCalculate": "गणना करें",
        "fertBuy": "क्या ख़रीदें",
        "fertUrea": "यूरिया",
        "fertDap": "डीएपी",
        "fertMop": "एमओपी",
        "fertKg": "{value} कि.ग्रा.",
        "fertBags": "लगभग {count} बोरी (50 कि.ग्रा.)",
        "fertCost": "लगभग ₹{amount}",
        "fertCostNote": "अनुमानित दुकान भाव से आकलन, पक्का भाव नहीं।",
        "fertReduced": "आपकी मिट्टी जाँच से मात्रा घटी — कम ख़रीदना पड़ेगा।",
        "fertSplitNote": "नाइट्रोजन 2–3 बार में दें, बुवाई के समय पूरा नहीं।",
        "onboardTitle": "अपने खेत के बारे में बताएँ",
        "onboardWhy": "इससे हम आपके इलाक़े और फ़सल के हिसाब से सलाह दे पाएँगे।",
        "onboardName": "आपका नाम",
        "onboardMobile": "मोबाइल नंबर",
        "onboardVillage": "गाँव",
        "onboardDistrict": "ज़िला",
        "onboardMainCrop": "मुख्य फ़सल",
        "onboardFinish": "आगे बढ़ें",
        "onboardSkip": "अभी छोड़ें",
        "communityTitle": "किसान समुदाय",
        "communityEmpty": "अभी कोई पोस्ट नहीं",
        "communityHelpful": "उपयोगी",
        "communityComments": "{count} जवाब",
        "communityAsk": "किसानों से पूछें",
        "communityPostTitle": "समस्या क्या है?",
        "communityDetails": "विस्तार से बताएँ",
        "communityCrop": "फ़सल",
        "communityPost": "पोस्ट करें",
        "communityPosting": "पोस्ट हो रहा है",
        "communityAddComment": "जवाब लिखें",
        "communitySend": "भेजें",
        "communityNoComments": "अभी कोई जवाब नहीं। पहले आप लिखें।",
        "communitySignInNote": "जवाब देने या उपयोगी बताने के लिए साइन इन करें।",
        "homeGreeting": "नमस्ते, {name}",
        "homeMyCrops": "मेरी फ़सलें",
        "farmNoFields": "अभी कोई खेत नहीं",
        "farmNoFieldsHint": "सलाह पाने के लिए अपना पहला खेत जोड़ें।",
        "farmAddField": "खेत जोड़ें",
        "farmAddCrop": "फ़सल जोड़ें",
        "farmFieldName": "खेत का नाम",
        "farmArea": "क्षेत्रफल",
        "farmVillage": "गाँव",
        "farmTaluka": "तालुका",
        "farmDistrict": "ज़िला",
        "farmState": "राज्य",
        "farmSoilType": "मिट्टी का प्रकार",
        "farmIrrigation": "सिंचाई",
        "farmWaterSource": "पानी का स्रोत",
        "farmFrequency": "पानी देना",
        "farmPreviousCrop": "पिछली फ़सल",
        "farmCropName": "फ़सल",
        "farmVariety": "किस्म",
        "farmSowingDate": "बुवाई की तारीख़",
        "farmCultivationMethod": "कैसे बोया",
        "farmNotes": "टिप्पणी",
        "farmStep": "चरण {current} / {total}",
        "farmNext": "आगे",
        "farmBack": "पीछे",
        "farmSave": "सहेजें",
        "farmSaving": "सहेजा जा रहा है",
        "farmReview": "अपने जवाब जाँचें",
        "farmDayCount": "दिन {days}",
        "farmDelete": "हटाएँ",
        "farmDeleteField": "यह खेत हटाएँ?",
        "farmDeleteFieldNote": "इसमें मौजूद फ़सलें भी हट जाएँगी।",
        "farmCancel": "रद्द करें",
        "farmRequired": "कृपया यह भरें",
        "farmBadNumber": "संख्या डालें",
        "farmUseLocation": "मेरा स्थान लें",
        "farmFields": "खेत",
        "farmCrops": "फ़सलें",
        "farmNoCrops": "इस खेत में अभी कोई फ़सल नहीं",
        "farmSaved": "सहेजा गया",
        "authTagline": "आपका खेती साथी",
        "authGoogle": "Google से जारी रखें",
        "authSigningIn": "साइन इन हो रहा है",
        "authCancelled": "साइन इन रद्द कर दिया गया।",
        "authRejected": "Google साइन इन नहीं कर सका। फिर कोशिश करें।",
        "authStateMismatch": "यह साइन इन लिंक मेल नहीं खाया। कृपया दोबारा शुरू करें।",
        "authServerError": "अभी साइन इन नहीं हो सका।",
        "authOffline": "आप ऑफ़लाइन हैं। कनेक्ट करके फिर कोशिश करें।",
        "authSignOut": "साइन आउट",
        "authProfile": "प्रोफ़ाइल",
        "authWhyGoogle": "हम आपका Google खाता इस्तेमाल करते हैं ताकि पासवर्ड याद रखना न पड़े।",
        "mandiIndicative": "संकेतक भाव",
        "mandiIndicativeNote": "असली सरकारी आँकड़े, पर आज आपकी स्थानीय मंडी का ताज़ा भाव नहीं।",
        "weatherSearchHint": "गाँव, कस्बा या ज़िला",
        "weatherUseLocation": "मेरा स्थान लें",
        "weatherForecast": "अगले दिन",
        "weatherLocating": "आपका स्थान खोजा जा रहा है",
        "weatherLocationDenied": "स्थान बंद है। अपने गाँव का नाम खोजें।",
        "weatherRain": "{value}% बारिश की संभावना",
        "weatherFeels": "महसूस {value}°",
        "weatherHumidity": "नमी",
        "weatherWind": "हवा",
        "weatherSprayWarn": "बारिश की संभावना — आज छिड़काव न करें।",
        "weatherHeatWarn": "बहुत गर्मी। सुबह जल्दी या शाम को सिंचाई करें।",
        "weatherWindWarn": "तेज़ हवा — छिड़काव बह जाएगा। हवा शांत होने तक रुकें।",
        "mandiTitle": "मंडी भाव",
        "mandiCrop": "फ़सल",
        "mandiState": "राज्य",
        "mandiPerQuintal": "प्रति क्विंटल",
        "mandiRange": "दायरा {min} – {max}",
        "mandiLive": "सरकारी लाइव भाव",
        "mandiEstimate": "अनुमानित भाव",
        "mandiEstimateNote": "यहाँ इस फ़सल का लाइव भाव उपलब्ध नहीं है। यह सरकारी आधार दर है, बिका हुआ भाव नहीं।",
        "mandiArrival": "मंडी तिथि {date}",
        "mandiNotYourDistrict": "निकटतम मंडी",
        "diagnoseUnclear": "फ़ोटो पर्याप्त स्पष्ट नहीं थी",
        "diagnoseHowToFix": "अच्छी फ़ोटो कैसे लें",
        "diagnoseGuide": "एक प्रभावित पत्ते को पूरे फ्रेम में लें",
        "diagnoseTakePhoto": "फ़ोटो लें",
        "diagnoseGallery": "गैलरी से चुनें",
        "diagnoseCompressing": "फ़ोटो तैयार हो रही है",
        "diagnoseUploading": "भेजा जा रहा है",
        "diagnoseAnalysing": "पत्ते की जाँच हो रही है",
        "diagnoseMatching": "इलाज खोजा जा रहा है",
        "diagnoseSlowNote": "दिन की पहली जाँच में एक मिनट तक लग सकता है।",
        "diagnoseHealthy": "स्वस्थ",
        "diagnoseInfected": "रोग मिला",
        "diagnoseConfidence": "{value}% निश्चित",
        "diagnoseWhatToDo": "अभी क्या करें",
        "diagnoseFarmingSteps": "खेती के उपाय",
        "diagnoseSymptoms": "क्या देखें",
        "diagnoseCauses": "ऐसा क्यों हुआ",
        "diagnoseBuy": "उपयोग करने के उत्पाद",
        "diagnoseExpertNote": "छिड़काव से पहले कृपया विशेषज्ञ से पुष्टि करें।",
        "diagnoseRetake": "दूसरा पत्ता जाँचें",
        "diagnoseTooLarge": "यह फ़ोटो बहुत बड़ी है। कृपया नई फ़ोटो लें।",
        "diagnoseNoCamera": "इस फ़ोन में कैमरा उपलब्ध नहीं है।",
        "diagnosePermission": "फ़सल जाँचने के लिए कैमरा चालू करने दें।",
        "diagnoseKeepPhoto": "आपकी फ़ोटो सुरक्षित है। आप दोबारा कोशिश कर सकते हैं।",
        "appOffline": "आप ऑफ़लाइन हैं। सहेजी गई जानकारी दिखा रहे हैं।",
        "appSlow": "इसमें सामान्य से अधिक समय लग रहा है। कृपया प्रतीक्षा करें।",
        "appError": "कुछ गड़बड़ हो गई।",
        "appRetry": "फिर कोशिश करें",
        "appLastUpdated": "{time} को अपडेट किया गया",
        "appLanguage": "भाषा",
        "navDiagnose": "जाँच",
        "navFarm": "मेरा खेत",
        "navInsights": "जानकारी",
        "navMore": "और",
        "comingSoon": "जल्द आ रहा है",
    },
    "gu": {
        "profileEdit": "પ્રોફાઇલ બદલો",
        "profileSaved": "સાચવ્યું",
        "productsTitle": "ઉત્પાદનો",
        "productsSearch": "ઉત્પાદન શોધો",
        "productsUsage": "કેવી રીતે વાપરવું",
        "productsFeatures": "કેમ ઉપયોગી છે",
        "productsPrice": "₹{amount}",
        "productsNone": "આ શોધથી કોઈ ઉત્પાદન મળ્યું નહીં",
        "productsStaticNote": "સામાન્ય ખેતી સામગ્રીની સંદર્ભ યાદી. ભાવ અંદાજિત છે — તમારા ડીલર પાસે ચકાસો.",
        "predTabMandi": "બજાર",
        "predTabYield": "ઉપજ",
        "predTabProfit": "નફો",
        "predCrop": "પાક",
        "predArea": "વિસ્તાર (એકર)",
        "predNdvi": "પાકની હરિયાળી (NDVI)",
        "predNdviHelp": "ઉપરથી પાક કેટલો લીલો અને તંદુરસ્ત દેખાય છે. ખબર ન હોય તો એમ જ રહેવા દો.",
        "predSoilMoisture": "જમીનનો ભેજ (%)",
        "predRainfall": "મોસમનો વરસાદ (મિ.મી.)",
        "predFertCost": "ખાતરનો ખર્ચ (₹)",
        "predPestCost": "દવાનો ખર્ચ (₹)",
        "predIrrigCost": "પિયતનો ખર્ચ (₹)",
        "predRun": "અંદાજ કાઢો",
        "predRunning": "ગણતરી થઈ રહી છે",
        "predYieldResult": "અંદાજિત ઉપજ",
        "predTonnes": "{value} ટન",
        "predPerAcre": "{value} ટન પ્રતિ એકર",
        "predVsRegion": "પ્રાદેશિક સરેરાશ {value} ટન પ્રતિ એકર",
        "predAbove": "તમારા વિસ્તાર કરતાં {value}% વધુ",
        "predBelow": "તમારા વિસ્તાર કરતાં {value}% ઓછું",
        "predRevenue": "અંદાજિત આવક",
        "predCosts": "તમારો ખર્ચ",
        "predMargin": "ખર્ચ પછી બચત",
        "predMarginNote": "આમાં ફક્ત તમે નાખેલ ખાતર, દવા અને પિયત ગણ્યાં છે. બિયારણ, મજૂરી, જમીન અને વાહનખર્ચ નથી, તેથી સાચો નફો ઓછો હશે.",
        "predPrice": "₹{value} પ્રતિ ક્વિન્ટલ",
        "predConfidence": "{value}% ખાતરી",
        "predEstimatedPrice": "આ અંદાજ આધાર ભાવ પર છે, જીવંત બજાર ભાવ પર નહીં.",
        "predFallbackNote": "આગાહી મોડલ સુધી પહોંચી શકાયું નહીં, તેથી આ આ પાકના સરેરાશ આંકડા પરથી તૈયાર કરેલો અંદાજ છે.",
        "advisoryTitle": "પાક કૅલેન્ડર",
        "advisoryNoCrops": "ખેતર અને પાક ઉમેરો, પછી આ પાનું દરેક તબક્કે શું કરવું તે જણાવશે.",
        "advisoryNoneForCrop": "આ પાક માટે હજુ તબક્કાવાર માર્ગદર્શન નથી.",
        "advisoryNothingDue": "હમણાં કંઈ કરવાનું નથી. આગળનું પગલું નીચે છે.",
        "advisoryNow": "હમણાં આ કરો",
        "advisoryNextIn": "આગળ, {days} દિવસમાં",
        "advisoryDone": "{count} અગાઉના તબક્કા પસાર ચૂક્યા છે",
        "advisoryDose": "તમારા ખેતર માટે {amount}",
        "advisoryGeneralNote": "આ પાકની ઉંમર પ્રમાણે સામાન્ય માર્ગદર્શન છે, તમારા ખેતરની તપાસ નહીં. છંટકાવ પહેલાં પાક જાતે જુઓ અને પેક પરની સૂચના પાળો.",
        "predQuintals": "{value} ક્વિન્ટલ",
        "predLoss": "કદાચ ખર્ચ પણ નહીં નીકળે.",
        "schemesTitle": "સરકારી યોજનાઓ",
        "schemesSearch": "યોજના શોધો",
        "schemesAll": "બધી",
        "schemesNone": "આ શોધથી કોઈ યોજના મળી નહીં",
        "schemesBenefits": "શું મળશે",
        "schemesEligibility": "કોણ અરજી કરી શકે",
        "schemesOpen": "સત્તાવાર વેબસાઇટ ખોલો",
        "schemesLaunched": "{when} માં શરૂ",
        "schemesCuratedNote": "આ ચકાસેલી યાદી છે, સરકારી લાઇવ ફીડ નથી. વિગતો સત્તાવાર સાઇટ પર ચકાસો.",
        "fertTitle": "ખાતર કૅલ્ક્યુલેટર",
        "fertCrop": "પાક",
        "fertArea": "વિસ્તાર (એકર)",
        "fertSoil": "જમીનનો પ્રકાર",
        "fertSoilTest": "મારી પાસે જમીન ચકાસણી છે",
        "fertExistingN": "જમીનમાં નાઇટ્રોજન (કિ.ગ્રા./એકર)",
        "fertExistingP": "જમીનમાં ફોસ્ફરસ (કિ.ગ્રા./એકર)",
        "fertExistingK": "જમીનમાં પોટાશ (કિ.ગ્રા./એકર)",
        "fertCalculate": "ગણતરી કરો",
        "fertBuy": "શું ખરીદવું",
        "fertUrea": "યુરિયા",
        "fertDap": "ડીએપી",
        "fertMop": "એમઓપી",
        "fertKg": "{value} કિ.ગ્રા.",
        "fertBags": "આશરે {count} બોરી (50 કિ.ગ્રા.)",
        "fertCost": "આશરે ₹{amount}",
        "fertCostNote": "અંદાજિત દુકાન ભાવ પરથી અંદાજ, પાકો ભાવ નથી.",
        "fertReduced": "તમારી જમીન ચકાસણીથી માત્રા ઘટી — ઓછું ખરીદવું પડશે.",
        "fertSplitNote": "નાઇટ્રોજન 2–3 વારમાં આપો, વાવણી વખતે બધું નહીં.",
        "onboardTitle": "તમારા ખેતર વિશે જણાવો",
        "onboardWhy": "આથી અમે તમારા વિસ્તાર અને પાક પ્રમાણે સલાહ આપી શકીશું.",
        "onboardName": "તમારું નામ",
        "onboardMobile": "મોબાઇલ નંબર",
        "onboardVillage": "ગામ",
        "onboardDistrict": "જિલ્લો",
        "onboardMainCrop": "મુખ્ય પાક",
        "onboardFinish": "આગળ વધો",
        "onboardSkip": "હમણાં છોડો",
        "communityTitle": "ખેડૂત સમુદાય",
        "communityEmpty": "હજી કોઈ પોસ્ટ નથી",
        "communityHelpful": "ઉપયોગી",
        "communityComments": "{count} જવાબ",
        "communityAsk": "ખેડૂતોને પૂછો",
        "communityPostTitle": "સમસ્યા શું છે?",
        "communityDetails": "વિગતે જણાવો",
        "communityCrop": "પાક",
        "communityPost": "પોસ્ટ કરો",
        "communityPosting": "પોસ્ટ થઈ રહ્યું છે",
        "communityAddComment": "જવાબ લખો",
        "communitySend": "મોકલો",
        "communityNoComments": "હજી કોઈ જવાબ નથી. પહેલા તમે લખો.",
        "communitySignInNote": "જવાબ આપવા કે ઉપયોગી કહેવા સાઇન ઇન કરો.",
        "homeGreeting": "નમસ્તે, {name}",
        "homeMyCrops": "મારા પાક",
        "farmNoFields": "હજી કોઈ ખેતર નથી",
        "farmNoFieldsHint": "સલાહ મેળવવા તમારું પહેલું ખેતર ઉમેરો.",
        "farmAddField": "ખેતર ઉમેરો",
        "farmAddCrop": "પાક ઉમેરો",
        "farmFieldName": "ખેતરનું નામ",
        "farmArea": "વિસ્તાર",
        "farmVillage": "ગામ",
        "farmTaluka": "તાલુકો",
        "farmDistrict": "જિલ્લો",
        "farmState": "રાજ્ય",
        "farmSoilType": "જમીનનો પ્રકાર",
        "farmIrrigation": "સિંચાઈ",
        "farmWaterSource": "પાણીનો સ્રોત",
        "farmFrequency": "પાણી આપવું",
        "farmPreviousCrop": "છેલ્લો પાક",
        "farmCropName": "પાક",
        "farmVariety": "જાત",
        "farmSowingDate": "વાવણી તારીખ",
        "farmCultivationMethod": "કેવી રીતે વાવ્યું",
        "farmNotes": "નોંધ",
        "farmStep": "પગલું {current} / {total}",
        "farmNext": "આગળ",
        "farmBack": "પાછળ",
        "farmSave": "સાચવો",
        "farmSaving": "સાચવી રહ્યા છીએ",
        "farmReview": "તમારા જવાબ તપાસો",
        "farmDayCount": "દિવસ {days}",
        "farmDelete": "કાઢી નાખો",
        "farmDeleteField": "આ ખેતર કાઢી નાખવું?",
        "farmDeleteFieldNote": "તેમાંના પાક પણ કાઢી નાખવામાં આવશે.",
        "farmCancel": "રદ કરો",
        "farmRequired": "કૃપા કરી આ ભરો",
        "farmBadNumber": "સંખ્યા દાખલ કરો",
        "farmUseLocation": "મારું સ્થાન લો",
        "farmFields": "ખેતર",
        "farmCrops": "પાક",
        "farmNoCrops": "આ ખેતરમાં હજી કોઈ પાક નથી",
        "farmSaved": "સાચવ્યું",
        "authTagline": "તમારો ખેતી સાથી",
        "authGoogle": "Google થી ચાલુ રાખો",
        "authSigningIn": "સાઇન ઇન થઈ રહ્યું છે",
        "authCancelled": "સાઇન ઇન રદ કરાયું.",
        "authRejected": "Google સાઇન ઇન કરી શક્યું નહીં. ફરી પ્રયાસ કરો.",
        "authStateMismatch": "આ સાઇન ઇન લિંક મેળ ખાતી નથી. કૃપા કરી ફરી શરૂ કરો.",
        "authServerError": "અત્યારે સાઇન ઇન થઈ શક્યું નહીં.",
        "authOffline": "તમે ઑફલાઇન છો. જોડાઈને ફરી પ્રયાસ કરો.",
        "authSignOut": "સાઇન આઉટ",
        "authProfile": "પ્રોફાઇલ",
        "authWhyGoogle": "અમે તમારું Google ખાતું વાપરીએ છીએ જેથી પાસવર્ડ યાદ રાખવો ન પડે.",
        "mandiIndicative": "સૂચક ભાવ",
        "mandiIndicativeNote": "સાચા સરકારી આંકડા, પણ આજના તમારા સ્થાનિક બજારનો તાજો ભાવ નથી.",
        "weatherSearchHint": "ગામ, શહેર કે જિલ્લો",
        "weatherUseLocation": "મારું સ્થાન લો",
        "weatherForecast": "આવતા દિવસો",
        "weatherLocating": "તમારું સ્થાન શોધી રહ્યા છીએ",
        "weatherLocationDenied": "સ્થાન બંધ છે. તમારા ગામનું નામ શોધો.",
        "weatherRain": "{value}% વરસાદની શક્યતા",
        "weatherFeels": "અનુભવ {value}°",
        "weatherHumidity": "ભેજ",
        "weatherWind": "પવન",
        "weatherSprayWarn": "વરસાદની શક્યતા — આજે છંટકાવ ન કરો.",
        "weatherHeatWarn": "બહુ ગરમી. વહેલી સવારે કે સાંજે પિયત કરો.",
        "weatherWindWarn": "તેજ પવન — છંટકાવ ઊડી જશે. પવન શાંત થવા દો.",
        "mandiTitle": "માર્કેટ ભાવ",
        "mandiCrop": "પાક",
        "mandiState": "રાજ્ય",
        "mandiPerQuintal": "પ્રતિ ક્વિન્ટલ",
        "mandiRange": "રેન્જ {min} – {max}",
        "mandiLive": "સરકારી લાઇવ ભાવ",
        "mandiEstimate": "અંદાજિત ભાવ",
        "mandiEstimateNote": "અહીં આ પાકનો લાઇવ ભાવ ઉપલબ્ધ નથી. આ સરકારી આધાર દર છે, વેચાયેલો ભાવ નથી.",
        "mandiArrival": "બજાર તારીખ {date}",
        "mandiNotYourDistrict": "નજીકનું બજાર",
        "diagnoseUnclear": "ફોટો પૂરતો સ્પષ્ટ ન હતો",
        "diagnoseHowToFix": "સારો ફોટો કેવી રીતે લેવો",
        "diagnoseGuide": "એક અસરગ્રસ્ત પાનને આખી ફ્રેમમાં લો",
        "diagnoseTakePhoto": "ફોટો લો",
        "diagnoseGallery": "ગેલેરીમાંથી પસંદ કરો",
        "diagnoseCompressing": "ફોટો તૈયાર થઈ રહ્યો છે",
        "diagnoseUploading": "મોકલી રહ્યા છીએ",
        "diagnoseAnalysing": "પાનની તપાસ થઈ રહી છે",
        "diagnoseMatching": "ઉપચાર શોધી રહ્યા છીએ",
        "diagnoseSlowNote": "દિવસની પહેલી તપાસમાં એક મિનિટ લાગી શકે છે.",
        "diagnoseHealthy": "તંદુરસ્ત",
        "diagnoseInfected": "રોગ મળ્યો",
        "diagnoseConfidence": "{value}% ખાતરી",
        "diagnoseWhatToDo": "હવે શું કરવું",
        "diagnoseFarmingSteps": "ખેતીના ઉપાય",
        "diagnoseSymptoms": "શું જોવું",
        "diagnoseCauses": "આવું કેમ થયું",
        "diagnoseBuy": "વાપરવાના ઉત્પાદનો",
        "diagnoseExpertNote": "છંટકાવ પહેલાં નિષ્ણાતની ખાતરી કરો.",
        "diagnoseRetake": "બીજું પાન તપાસો",
        "diagnoseTooLarge": "આ ફોટો બહુ મોટો છે. કૃપા કરીને નવો ફોટો લો.",
        "diagnoseNoCamera": "આ ફોનમાં કૅમેરા ઉપલબ્ધ નથી.",
        "diagnosePermission": "પાક તપાસવા માટે કૅમેરાની પરવાનગી આપો.",
        "diagnoseKeepPhoto": "તમારો ફોટો સાચવેલો છે. તમે ફરી પ્રયાસ કરી શકો છો.",
        "appOffline": "તમે ઑફલાઇન છો. સાચવેલી માહિતી બતાવી રહ્યા છીએ.",
        "appSlow": "આમાં સામાન્ય કરતાં વધુ સમય લાગી રહ્યો છે. કૃપા કરીને રાહ જુઓ.",
        "appError": "કંઈક ખોટું થયું.",
        "appRetry": "ફરી પ્રયાસ કરો",
        "appLastUpdated": "{time} એ અપડેટ થયું",
        "appLanguage": "ભાષા",
        "navDiagnose": "તપાસ",
        "navFarm": "મારું ખેતર",
        "navInsights": "માહિતી",
        "navMore": "વધુ",
        "comingSoon": "ટૂંક સમયમાં",
    },
    "mr": {
        "profileEdit": "प्रोफाइल बदला",
        "profileSaved": "जतन केले",
        "productsTitle": "उत्पादने",
        "productsSearch": "उत्पादन शोधा",
        "productsUsage": "कसे वापरावे",
        "productsFeatures": "का उपयुक्त आहे",
        "productsPrice": "₹{amount}",
        "productsNone": "या शोधाशी जुळणारे उत्पादन नाही",
        "productsStaticNote": "सामान्य शेती साहित्याची संदर्भ यादी. दर अंदाजित आहेत — तुमच्या विक्रेत्याकडे तपासा.",
        "predTabMandi": "बाजार",
        "predTabYield": "उत्पादन",
        "predTabProfit": "नफा",
        "predCrop": "पीक",
        "predArea": "क्षेत्र (एकर)",
        "predNdvi": "पिकाची हिरवळ (NDVI)",
        "predNdviHelp": "वरून पीक किती हिरवे आणि निरोगी दिसते. माहीत नसल्यास तसेच ठेवा.",
        "predSoilMoisture": "मातीतील ओलावा (%)",
        "predRainfall": "हंगामातील पाऊस (मि.मी.)",
        "predFertCost": "खताचा खर्च (₹)",
        "predPestCost": "औषधाचा खर्च (₹)",
        "predIrrigCost": "पाण्याचा खर्च (₹)",
        "predRun": "अंदाज काढा",
        "predRunning": "गणना सुरू आहे",
        "predYieldResult": "अपेक्षित उत्पादन",
        "predTonnes": "{value} टन",
        "predPerAcre": "{value} टन प्रति एकर",
        "predVsRegion": "प्रादेशिक सरासरी {value} टन प्रति एकर",
        "predAbove": "तुमच्या भागापेक्षा {value}% जास्त",
        "predBelow": "तुमच्या भागापेक्षा {value}% कमी",
        "predRevenue": "अपेक्षित उत्पन्न",
        "predCosts": "तुमचा खर्च",
        "predMargin": "खर्चानंतर शिल्लक",
        "predMarginNote": "यात फक्त तुम्ही टाकलेले खत, औषध आणि पाणी मोजले आहे. बियाणे, मजुरी, जमीन आणि वाहतूक नाही, त्यामुळे खरा नफा कमी असेल.",
        "predPrice": "₹{value} प्रति क्विंटल",
        "predConfidence": "{value}% खात्री",
        "predEstimatedPrice": "हा अंदाज आधारभूत दरावर आहे, थेट बाजारभावावर नाही.",
        "predFallbackNote": "अंदाज मॉडेलपर्यंत पोहोचता आले नाही, म्हणून हा या पिकाच्या सरासरी आकडेवारीवरून केलेला साधारण अंदाज आहे.",
        "advisoryTitle": "पीक दिनदर्शिका",
        "advisoryNoCrops": "शेत आणि पीक जोडा, मग हे पान प्रत्येक टप्प्यावर काय करायचे ते सांगेल.",
        "advisoryNoneForCrop": "या पिकासाठी अजून टप्पा मार्गदर्शन नाही.",
        "advisoryNothingDue": "सध्या काही करायचे नाही. पुढची पायरी खाली आहे.",
        "advisoryNow": "आता हे करा",
        "advisoryNextIn": "पुढे, {days} दिवसांनी",
        "advisoryDone": "{count} मागील टप्पे संपले आहेत",
        "advisoryDose": "तुमच्या शेतासाठी {amount}",
        "advisoryGeneralNote": "हे पिकाच्या वयानुसार सर्वसाधारण मार्गदर्शन आहे, तुमच्या शेताची पाहणी नव्हे. फवारणीपूर्वी पीक स्वतः पाहा आणि पाकिटावरील सूचना पाळा.",
        "predQuintals": "{value} क्विंटल",
        "predLoss": "कदाचित खर्चही निघणार नाही.",
        "schemesTitle": "शासकीय योजना",
        "schemesSearch": "योजना शोधा",
        "schemesAll": "सर्व",
        "schemesNone": "या शोधाशी जुळणारी योजना नाही",
        "schemesBenefits": "काय मिळेल",
        "schemesEligibility": "कोण अर्ज करू शकते",
        "schemesOpen": "अधिकृत संकेतस्थळ उघडा",
        "schemesLaunched": "{when} मध्ये सुरू",
        "schemesCuratedNote": "ही तपासलेली यादी आहे, शासकीय थेट फीड नाही. तपशील अधिकृत संकेतस्थळावर तपासा.",
        "fertTitle": "खत कॅल्क्युलेटर",
        "fertCrop": "पीक",
        "fertArea": "क्षेत्र (एकर)",
        "fertSoil": "मातीचा प्रकार",
        "fertSoilTest": "माझ्याकडे माती परीक्षण आहे",
        "fertExistingN": "मातीत नायट्रोजन (कि.ग्रा./एकर)",
        "fertExistingP": "मातीत फॉस्फरस (कि.ग्रा./एकर)",
        "fertExistingK": "मातीत पोटॅश (कि.ग्रा./एकर)",
        "fertCalculate": "गणना करा",
        "fertBuy": "काय खरेदी करावे",
        "fertUrea": "युरिया",
        "fertDap": "डीएपी",
        "fertMop": "एमओपी",
        "fertKg": "{value} कि.ग्रा.",
        "fertBags": "अंदाजे {count} पोती (50 कि.ग्रा.)",
        "fertCost": "अंदाजे ₹{amount}",
        "fertCostNote": "अंदाजित दुकान दरांवरून अंदाज, ठरलेला दर नाही.",
        "fertReduced": "तुमच्या माती परीक्षणाने मात्रा कमी झाली — कमी खरेदी करावी लागेल.",
        "fertSplitNote": "नायट्रोजन 2–3 हप्त्यांत द्या, पेरणीच्या वेळी सर्व नाही.",
        "onboardTitle": "तुमच्या शेताबद्दल सांगा",
        "onboardWhy": "यामुळे आम्ही तुमच्या भागानुसार आणि पिकानुसार सल्ला देऊ शकू.",
        "onboardName": "तुमचे नाव",
        "onboardMobile": "मोबाइल नंबर",
        "onboardVillage": "गाव",
        "onboardDistrict": "जिल्हा",
        "onboardMainCrop": "मुख्य पीक",
        "onboardFinish": "पुढे जा",
        "onboardSkip": "आत्ता वगळा",
        "communityTitle": "शेतकरी समुदाय",
        "communityEmpty": "अजून पोस्ट नाही",
        "communityHelpful": "उपयुक्त",
        "communityComments": "{count} उत्तरे",
        "communityAsk": "शेतकऱ्यांना विचारा",
        "communityPostTitle": "समस्या काय आहे?",
        "communityDetails": "सविस्तर सांगा",
        "communityCrop": "पीक",
        "communityPost": "पोस्ट करा",
        "communityPosting": "पोस्ट होत आहे",
        "communityAddComment": "उत्तर लिहा",
        "communitySend": "पाठवा",
        "communityNoComments": "अजून उत्तर नाही. पहिले तुम्ही लिहा.",
        "communitySignInNote": "उत्तर देण्यासाठी किंवा उपयुक्त म्हणण्यासाठी साइन इन करा.",
        "homeGreeting": "नमस्ते, {name}",
        "homeMyCrops": "माझी पिके",
        "farmNoFields": "अजून शेत नाही",
        "farmNoFieldsHint": "सल्ला मिळवण्यासाठी तुमचे पहिले शेत जोडा.",
        "farmAddField": "शेत जोडा",
        "farmAddCrop": "पीक जोडा",
        "farmFieldName": "शेताचे नाव",
        "farmArea": "क्षेत्र",
        "farmVillage": "गाव",
        "farmTaluka": "तालुका",
        "farmDistrict": "जिल्हा",
        "farmState": "राज्य",
        "farmSoilType": "मातीचा प्रकार",
        "farmIrrigation": "सिंचन",
        "farmWaterSource": "पाण्याचा स्रोत",
        "farmFrequency": "पाणी देणे",
        "farmPreviousCrop": "मागील पीक",
        "farmCropName": "पीक",
        "farmVariety": "जात",
        "farmSowingDate": "पेरणीची तारीख",
        "farmCultivationMethod": "कसे पेरले",
        "farmNotes": "टिपा",
        "farmStep": "पायरी {current} / {total}",
        "farmNext": "पुढे",
        "farmBack": "मागे",
        "farmSave": "जतन करा",
        "farmSaving": "जतन करत आहे",
        "farmReview": "तुमची उत्तरे तपासा",
        "farmDayCount": "दिवस {days}",
        "farmDelete": "काढून टाका",
        "farmDeleteField": "हे शेत काढायचे?",
        "farmDeleteFieldNote": "त्यातील पिकेही काढली जातील.",
        "farmCancel": "रद्द करा",
        "farmRequired": "कृपया हे भरा",
        "farmBadNumber": "संख्या टाका",
        "farmUseLocation": "माझे स्थान घ्या",
        "farmFields": "शेत",
        "farmCrops": "पिके",
        "farmNoCrops": "या शेतात अजून पीक नाही",
        "farmSaved": "जतन केले",
        "authTagline": "तुमचा शेती सोबती",
        "authGoogle": "Google ने पुढे जा",
        "authSigningIn": "साइन इन होत आहे",
        "authCancelled": "साइन इन रद्द झाले.",
        "authRejected": "Google साइन इन करू शकले नाही. पुन्हा प्रयत्न करा.",
        "authStateMismatch": "ही साइन इन लिंक जुळली नाही. कृपया पुन्हा सुरू करा.",
        "authServerError": "आत्ता साइन इन होऊ शकले नाही.",
        "authOffline": "तुम्ही ऑफलाइन आहात. जोडून पुन्हा प्रयत्न करा.",
        "authSignOut": "साइन आउट",
        "authProfile": "प्रोफाइल",
        "authWhyGoogle": "आम्ही तुमचे Google खाते वापरतो जेणेकरून पासवर्ड लक्षात ठेवावा लागणार नाही.",
        "mandiIndicative": "निर्देशक दर",
        "mandiIndicativeNote": "खरी सरकारी माहिती, पण आजचा तुमच्या स्थानिक बाजाराचा ताजा दर नाही.",
        "weatherSearchHint": "गाव, शहर किंवा जिल्हा",
        "weatherUseLocation": "माझे स्थान घ्या",
        "weatherForecast": "पुढील दिवस",
        "weatherLocating": "तुमचे स्थान शोधत आहे",
        "weatherLocationDenied": "स्थान बंद आहे. तुमच्या गावाचे नाव शोधा.",
        "weatherRain": "{value}% पावसाची शक्यता",
        "weatherFeels": "जाणवते {value}°",
        "weatherHumidity": "आर्द्रता",
        "weatherWind": "वारा",
        "weatherSprayWarn": "पाऊस अपेक्षित — आज फवारणी करू नका.",
        "weatherHeatWarn": "खूप उष्णता. पहाटे किंवा संध्याकाळी पाणी द्या.",
        "weatherWindWarn": "जोरदार वारा — फवारणी वाहून जाईल. वारा शांत होऊ द्या.",
        "mandiTitle": "बाजार भाव",
        "mandiCrop": "पीक",
        "mandiState": "राज्य",
        "mandiPerQuintal": "प्रति क्विंटल",
        "mandiRange": "श्रेणी {min} – {max}",
        "mandiLive": "सरकारी थेट दर",
        "mandiEstimate": "अंदाजित दर",
        "mandiEstimateNote": "येथे या पिकाचा थेट दर उपलब्ध नाही. हा सरकारी आधार दर आहे, विकला गेलेला भाव नाही.",
        "mandiArrival": "बाजार दिनांक {date}",
        "mandiNotYourDistrict": "जवळचे बाजार",
        "diagnoseUnclear": "फोटो पुरेसा स्पष्ट नव्हता",
        "diagnoseHowToFix": "चांगला फोटो कसा काढावा",
        "diagnoseGuide": "एक बाधित पान पूर्ण फ्रेममध्ये घ्या",
        "diagnoseTakePhoto": "फोटो काढा",
        "diagnoseGallery": "गॅलरीमधून निवडा",
        "diagnoseCompressing": "फोटो तयार होत आहे",
        "diagnoseUploading": "पाठवत आहे",
        "diagnoseAnalysing": "पानाची तपासणी होत आहे",
        "diagnoseMatching": "उपचार शोधत आहे",
        "diagnoseSlowNote": "दिवसातील पहिल्या तपासणीस एक मिनिट लागू शकतो.",
        "diagnoseHealthy": "निरोगी",
        "diagnoseInfected": "रोग आढळला",
        "diagnoseConfidence": "{value}% खात्री",
        "diagnoseWhatToDo": "आता काय करावे",
        "diagnoseFarmingSteps": "शेतीचे उपाय",
        "diagnoseSymptoms": "काय पहावे",
        "diagnoseCauses": "असे का झाले",
        "diagnoseBuy": "वापरायची उत्पादने",
        "diagnoseExpertNote": "फवारणीपूर्वी तज्ञांची खात्री करून घ्या.",
        "diagnoseRetake": "दुसरे पान तपासा",
        "diagnoseTooLarge": "हा फोटो खूप मोठा आहे. कृपया नवीन फोटो काढा.",
        "diagnoseNoCamera": "या फोनमध्ये कॅमेरा उपलब्ध नाही.",
        "diagnosePermission": "पीक तपासण्यासाठी कॅमेऱ्याची परवानगी द्या.",
        "diagnoseKeepPhoto": "तुमचा फोटो जतन केला आहे. तुम्ही पुन्हा प्रयत्न करू शकता.",
        "appOffline": "तुम्ही ऑफलाइन आहात. जतन केलेली माहिती दाखवत आहोत.",
        "appSlow": "यास नेहमीपेक्षा जास्त वेळ लागत आहे. कृपया प्रतीक्षा करा.",
        "appError": "काहीतरी चूक झाली.",
        "appRetry": "पुन्हा प्रयत्न करा",
        "appLastUpdated": "{time} रोजी अद्यतनित",
        "appLanguage": "भाषा",
        "navDiagnose": "तपासणी",
        "navFarm": "माझे शेत",
        "navInsights": "माहिती",
        "navMore": "अधिक",
        "comingSoon": "लवकरच येत आहे",
    },
}


def sanitize(segment):
    """Make one key segment a legal Dart identifier fragment.

    gen_l10n requires camelCase names with no punctuation, so `apple-scab`
    becomes `appleScab` and `2025-scheme` becomes `k2025Scheme`.
    """
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", segment) if p]
    if not parts:
        return ""
    head = parts[0]
    tail = "".join(p[0].upper() + p[1:] for p in parts[1:])
    return head + tail


def flatten(node, prefix, out):
    """Flatten nested dicts into underscore-joined keys, skipping non-strings."""
    for key, value in node.items():
        clean = sanitize(key)
        if not clean:
            continue
        name = f"{prefix}_{clean}" if prefix else clean
        if isinstance(value, dict):
            flatten(value, name, out)
        elif isinstance(value, str):
            out[name] = value
        # Lists and numbers have no ARB equivalent; they stay in Dart constants.


def camel_head(name):
    """dashboard_healthStatus -> lower-camel first segment, valid for gen_l10n."""
    name = sanitize(name)
    if not name:
        return name
    name = name[0].lower() + name[1:]
    return name if name[0].isalpha() else "k" + name


def build(locale, wanted_keys=None):
    path = os.path.join(MESSAGES_DIR, f"{locale}.json")
    with io.open(path, encoding="utf-8") as handle:
        data = json.load(handle)

    flat = {}
    for namespace in NAMESPACES:
        if namespace in data and isinstance(data[namespace], dict):
            flatten(data[namespace], camel_head(namespace), flat)

    flat.update(APP_EXTRAS.get(locale, {}))

    if wanted_keys is not None:
        flat = {k: v for k, v in flat.items() if k in wanted_keys}

    arb = {"@@locale": locale}
    for key in sorted(flat):
        value = flat[key]
        arb[key] = value
        names = sorted(set(PLACEHOLDER_RE.findall(value)))
        if names:
            arb[f"@{key}"] = {"placeholders": {n: {"type": "String"} for n in names}}
    return arb, set(flat)


def main():
    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)

    english, english_keys = build("en")
    written = {}

    for locale in LOCALES:
        # Non-English locales carry only keys English also has, so gen_l10n
        # never sees an orphan key with no template entry.
        arb, keys = build(locale, wanted_keys=english_keys)
        if locale != "en":
            # Strip metadata from non-template files; gen_l10n only reads it
            # from the template.
            arb = {k: v for k, v in arb.items() if not k.startswith("@") or k == "@@locale"}
        out_path = os.path.join(OUT_DIR, f"app_{locale}.arb")
        with io.open(out_path, "w", encoding="utf-8") as handle:
            json.dump(arb, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
        written[locale] = keys
        print(f"{out_path}: {len(keys)} keys")

    print()
    for locale in LOCALES:
        if locale == "en":
            continue
        missing = len(english_keys - written[locale])
        pct = 100 * (1 - missing / max(len(english_keys), 1))
        print(f"{locale}: {pct:.0f}% translated ({missing} keys fall back to English)")


if __name__ == "__main__":
    main()
