/**
 * AgriShield 360° — Phase 6 Risk Rules Registry
 *
 * Grounded in ICAR reference data:
 * - PestDiseaseReference (1,503 records)
 * - WeatherConditionReference (227 records)
 *
 * ZERO HALLUCINATION POLICY:
 * - Only verified ICAR rules are included.
 * - Rules with missing numeric thresholds are marked `isComputable: false`
 *   and explicitly return `INSUFFICIENT_DATA`.
 */

import { RiskRule } from './riskTypes';

export const VALIDATED_RISK_RULES: RiskRule[] = [
  // ── RICE RULES ─────────────────────────────────────────────────────────────
  {
    ruleId: 'RULE-RICE-SCAN-01',
    cropId: 'rice',
    threatId: 'rice_blast',
    threatName: 'Rice Blast (Magnaporthe oryzae)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Tillering', 'Panicle Initiation', 'Heading & Flowering'],
    geographicApplicability: ['All India', 'Gujarat', 'Maharashtra'],
    sourceReference: 'ICAR Annual Report 2022-23, 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: rice_neck-blast-magnaporthe-oryzae)',
    sourceEvidence: 'Screening of breeding lines for leaf and neck blast resistance under uniform blast nursery trials.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-RICE-SCAN-02',
    cropId: 'rice',
    threatId: 'rice_bacterial_leaf_blight',
    threatName: 'Bacterial Leaf Blight (Xanthomonas oryzae pv. oryzae)',
    threatCategory: 'BACTERIAL',
    applicableStageNames: ['Maximum Tillering', 'Heading & Flowering'],
    geographicApplicability: ['Punjab', 'Haryana', 'Coastal areas', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2022-23 p.27',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: rice_bacterial-leaf-blight)',
    sourceEvidence: 'Evaluation of Xa-gene introgressed lines against prevailing Xanthomonas oryzae pathotypes.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-RICE-SCAN-03',
    cropId: 'rice',
    threatId: 'rice_brown_spot',
    threatName: 'Brown Spot (Bipolaris oryzae)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Seedling', 'Tillering', 'Grain Filling'],
    geographicApplicability: ['Rainfed uplands', 'Shallow lowlands'],
    sourceReference: 'ICAR Annual Report 2022-23 p.27',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: rice_brown-spot)',
    sourceEvidence: 'Resistance screening in national disease nursery trials for upland rice varieties.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-RICE-SCAN-04',
    cropId: 'rice',
    threatId: 'rice_sheath_blight',
    threatName: 'Sheath Blight (Rhizoctonia solani)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Tillering', 'Panicle Exsertion'],
    geographicApplicability: ['Irrigated high-input ecologies'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: rice_sheath-blight)',
    sourceEvidence: 'Multi-location screening for sheath blight tolerance in semi-dwarf cultivars.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-RICE-SCAN-05',
    cropId: 'rice',
    threatId: 'rice_brown_planthopper',
    threatName: 'Brown Planthopper (Nilaparvata lugens)',
    threatCategory: 'INSECT_PEST',
    applicableStageNames: ['Maximum Tillering', 'Heading & Flowering'],
    geographicApplicability: ['Irrigated and coastal rice belts'],
    sourceReference: 'ICAR Annual Report 2022-23 p.28',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: rice_gall-midge-orseolia-oryzae)',
    sourceEvidence: 'BPH bioassay screening under controlled greenhouse and field infestation conditions.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },

  // ── WHEAT RULES ────────────────────────────────────────────────────────────
  {
    ruleId: 'RULE-WHEAT-SCAN-01',
    cropId: 'wheat',
    threatId: 'wheat_leaf_rust',
    threatName: 'Leaf Rust / Brown Rust (Puccinia triticina)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Heading, Anthesis & Grain Filling', 'Maturity & Ripening'],
    geographicApplicability: ['NWPZ', 'NEPZ', 'Central Zone', 'Peninsular Zone', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2022-23, 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: wheat_leaf-rust)',
    sourceEvidence: 'Adult plant resistance and seedling resistance testing against Pt pathotype 77-5.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-WHEAT-SCAN-02',
    cropId: 'wheat',
    threatId: 'wheat_stripe_rust',
    threatName: 'Stripe Rust / Yellow Rust (Puccinia striiformis)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Tillering & Jointing', 'Heading, Anthesis & Grain Filling'],
    geographicApplicability: ['NWPZ', 'Northern Hills Zone'],
    sourceReference: 'ICAR Annual Report 2022-23, 2024-25',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: wheat_stripe-rust)',
    sourceEvidence: 'Stripe rust severity scoring on advanced varietal trial lines using modified Cobb scale.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-WHEAT-SCAN-03',
    cropId: 'wheat',
    threatId: 'wheat_stem_rust',
    threatName: 'Stem Rust / Black Rust (Puccinia graminis f. sp. tritici)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Heading, Anthesis & Grain Filling', 'Maturity & Ripening'],
    geographicApplicability: ['Central Zone', 'Peninsular Zone', 'Madhya Pradesh', 'Maharashtra', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2022-23',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: wheat_stem-rust)',
    sourceEvidence: 'Field evaluation against virulent pathotypes 40A and 117-6 in Central India.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-WHEAT-SCAN-04',
    cropId: 'wheat',
    threatId: 'wheat_spot_blotch',
    threatName: 'Spot Blotch / Foliar Blight (Bipolaris sorokiniana)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Heading, Anthesis & Grain Filling'],
    geographicApplicability: ['NEPZ', 'Eastern UP', 'Bihar', 'West Bengal'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: wheat_spot-blotch)',
    sourceEvidence: 'Evaluation of spot blotch resistance under high temperature and humidity regimes in eastern gangetic plains.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-WHEAT-SCAN-05',
    cropId: 'wheat',
    threatId: 'wheat_powdery_mildew',
    threatName: 'Powdery Mildew (Blumeria graminis)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Tillering & Jointing', 'Heading, Anthesis & Grain Filling'],
    geographicApplicability: ['Northern Hills Zone'],
    sourceReference: 'ICAR Annual Report 2022-23',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: wheat_powdery-mildew)',
    sourceEvidence: 'Screening in temperate hill ecology under natural disease pressure.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },

  // ── COTTON RULES ───────────────────────────────────────────────────────────
  {
    ruleId: 'RULE-COTTON-SCAN-01',
    cropId: 'cotton',
    threatId: 'cotton_pink_bollworm',
    threatName: 'Pink Bollworm (Pectinophora gossypiella)',
    threatCategory: 'INSECT_PEST',
    applicableStageNames: ['Square Formation', 'Flowering & Boll Development', 'Boll Bursting & Maturity'],
    geographicApplicability: ['Central Zone', 'South Zone', 'Gujarat', 'Maharashtra'],
    sourceReference: 'ICAR Annual Report 2022-23 p.31',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: cotton_pink-bollworm)',
    sourceEvidence: 'Rosetted flower and green boll destruct monitoring for Cry1Ac/Cry2Ab survivorship.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-COTTON-SCAN-02',
    cropId: 'cotton',
    threatId: 'cotton_whitefly',
    threatName: 'Whitefly (Bemisia tabaci)',
    threatCategory: 'INSECT_PEST',
    applicableStageNames: ['Germination & Seedling', 'Square Formation'],
    geographicApplicability: ['North Zone', 'Central Zone', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2022-23, 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: cotton_whitefly)',
    sourceEvidence: 'Whitefly population dynamics and vector transmission indexing.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-COTTON-SCAN-03',
    cropId: 'cotton',
    threatId: 'cotton_leaf_curl_virus',
    threatName: 'Cotton Leaf Curl Virus (CLCuV)',
    threatCategory: 'VIRAL',
    applicableStageNames: ['Germination & Seedling', 'Square Formation'],
    geographicApplicability: ['North Zone', 'Punjab', 'Haryana', 'Rajasthan'],
    sourceReference: 'ICAR Annual Report 2022-23',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: cotton_leaf-curl-virus)',
    sourceEvidence: 'Evaluation of CLCuV disease index under hotspot screening trials.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-COTTON-SCAN-04',
    cropId: 'cotton',
    threatId: 'cotton_bacterial_blight',
    threatName: 'Bacterial Blight (Xanthomonas citri pv. malvacearum)',
    threatCategory: 'BACTERIAL',
    applicableStageNames: ['Square Formation', 'Flowering & Boll Development'],
    geographicApplicability: ['Central Zone', 'South Zone', 'Maharashtra', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: cotton_bacterial-blight)',
    sourceEvidence: 'Angular leaf spot and black arm symptom screening in breeding lines.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-COTTON-SCAN-05',
    cropId: 'cotton',
    threatId: 'cotton_alternaria_leaf_spot',
    threatName: 'Alternaria Leaf Spot (Alternaria macrospora)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Flowering & Boll Development', 'Boll Bursting & Maturity'],
    geographicApplicability: ['Central Zone', 'Gujarat', 'Maharashtra'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: cotton_alternaria-leaf-spot)',
    sourceEvidence: 'Foliar blight severity assessment in arboreum and hirsutum trials.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },

  // ── GROUNDNUT RULES ────────────────────────────────────────────────────────
  {
    ruleId: 'RULE-GND-SCAN-01',
    cropId: 'groundnut',
    threatId: 'groundnut_tikka_leaf_spot',
    threatName: 'Tikka Leaf Spot (Cercospora arachidicola / Phaeoisariopsis personata)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Flowering & Pegging', 'Pod Development & Harvest'],
    geographicApplicability: ['Gujarat (Saurashtra)', 'Andhra Pradesh', 'Tamil Nadu'],
    sourceReference: 'ICAR Annual Report 2022-23 p.34',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: groundnut_tikka-leaf-spot)',
    sourceEvidence: 'Late leaf spot and rust screening on 1–9 modified scale in AICRP trials.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-GND-SCAN-02',
    cropId: 'groundnut',
    threatId: 'groundnut_collar_rot',
    threatName: 'Collar Rot / Stem Rot (Sclerotium rolfsii)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Emergence & Vegetative'],
    geographicApplicability: ['Gujarat', 'Maharashtra', 'Karnataka'],
    sourceReference: 'ICAR Annual Report 2022-23',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: groundnut_collar-rot)',
    sourceEvidence: 'Seedling mortality evaluation in sick plots.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-GND-SCAN-03',
    cropId: 'groundnut',
    threatId: 'groundnut_bud_necrosis',
    threatName: 'Peanut Bud Necrosis Virus (PBNV)',
    threatCategory: 'VIRAL',
    applicableStageNames: ['Emergence & Vegetative', 'Flowering & Pegging'],
    geographicApplicability: ['Peninsular India', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: groundnut_peanut-bud-necrosis)',
    sourceEvidence: 'Vector transmission assays and field incidence recording.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },

  // ── SOYBEAN RULES ──────────────────────────────────────────────────────────
  {
    ruleId: 'RULE-SOY-SCAN-01',
    cropId: 'soybean',
    threatId: 'soybean_yellow_mosaic_virus',
    threatName: 'Yellow Mosaic Virus (YMV)',
    threatCategory: 'VIRAL',
    applicableStageNames: ['Emergence & Early Vegetative', 'Branching & Canopy Closure', 'Flowering & Pod Initiation'],
    geographicApplicability: ['Central Zone', 'Madhya Pradesh', 'Maharashtra'],
    sourceReference: 'ICAR Annual Report 2022-23 p.36',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: soybean_yellow-mosaic-virus)',
    sourceEvidence: 'Screening for mungbean yellow mosaic India virus resistance.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },
  {
    ruleId: 'RULE-SOY-SCAN-02',
    cropId: 'soybean',
    threatId: 'soybean_charcoal_rot',
    threatName: 'Charcoal Rot (Macrophomina phaseolina)',
    threatCategory: 'FUNGAL',
    applicableStageNames: ['Flowering & Pod Initiation', 'Seed Filling & Maturity'],
    geographicApplicability: ['Central Zone', 'Rainfed tracts'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_pest_disease_reference.json (Entry: soybean_charcoal-rot)',
    sourceEvidence: 'Evaluation under moisture stress conditions in sick plots.',
    requiredEvidence: ['SCAN_RESULT'],
    isComputable: true,
  },

  // ── NON-COMPUTABLE WEATHER STRESS RULES (RETURN INSUFFICIENT_DATA) ──────────
  {
    ruleId: 'RULE-WEATHER-WHEAT-01',
    cropId: 'wheat',
    threatId: 'wheat_terminal_heat',
    threatName: 'Terminal Heat Stress',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Heading, Anthesis & Grain Filling'],
    weatherConditionType: 'HEAT_STRESS',
    weatherConditionDescription: 'elevated temperature / heat stress',
    geographicApplicability: ['NWPZ', 'NEPZ', 'Central Zone'],
    sourceReference: 'ICAR Annual Report 2022-23 p.11',
    sourceDocument: 'crop_weather_conditions.json (Record 1)',
    sourceEvidence: 'Evaluated elevated temperature during flowering/grain filling. Numeric threshold is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report states qualitative "elevated temperature / heat stress" but omits computational numeric threshold.',
  },
  {
    ruleId: 'RULE-WEATHER-WHEAT-02',
    cropId: 'wheat',
    threatId: 'wheat_drought_stress',
    threatName: 'Vegetative Moisture Stress / Drought',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Tillering & Jointing', 'Heading, Anthesis & Grain Filling'],
    weatherConditionType: 'DROUGHT',
    weatherConditionDescription: 'drought / moisture stress',
    geographicApplicability: ['Rainfed and restricted irrigation ecologies'],
    sourceReference: 'ICAR Annual Report 2022-23 p.11',
    sourceDocument: 'crop_weather_conditions.json (Record 2)',
    sourceEvidence: 'Climate Resilient Agriculture / Crop Management. Numeric moisture deficit threshold is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report omits computational numeric drought/moisture deficit threshold.',
  },
  {
    ruleId: 'RULE-WEATHER-RICE-01',
    cropId: 'rice',
    threatId: 'rice_heat_stress_anthesis',
    threatName: 'High Temperature Stress (Floret Sterility)',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Heading & Flowering'],
    weatherConditionType: 'HEAT_STRESS',
    weatherConditionDescription: 'elevated temperature / heat stress',
    geographicApplicability: ['Central and Eastern India'],
    sourceReference: 'ICAR Annual Report 2022-23 p.11',
    sourceDocument: 'crop_weather_conditions.json (Record 3)',
    sourceEvidence: 'Climate Resilient Agriculture / Basic and Strategic Research. Numeric threshold is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report omits computational numeric floret sterility temperature threshold.',
  },
  {
    ruleId: 'RULE-WEATHER-RICE-02',
    cropId: 'rice',
    threatId: 'rice_drought_stress',
    threatName: 'Vegetative Drought Stress',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Seedling & Nursery', 'Tillering & Panicle Initiation'],
    weatherConditionType: 'DROUGHT',
    weatherConditionDescription: 'drought / moisture stress',
    geographicApplicability: ['Rainfed uplands'],
    sourceReference: 'ICAR Annual Report 2022-23 p.11',
    sourceDocument: 'crop_weather_conditions.json (Record 4)',
    sourceEvidence: 'Climate Resilient Agriculture / Basic and Strategic Research. Numeric threshold is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report omits computational numeric rainfall deficit threshold.',
  },
  {
    ruleId: 'RULE-WEATHER-COTTON-01',
    cropId: 'cotton',
    threatId: 'cotton_waterlogging',
    threatName: 'Waterlogging & Square Shedding',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Square Formation', 'Flowering & Boll Development'],
    weatherConditionType: 'SUBMERGENCE',
    weatherConditionDescription: 'waterlogging / submergence',
    geographicApplicability: ['Central Zone', 'Maharashtra', 'Gujarat'],
    sourceReference: 'ICAR Annual Report 2023-24',
    sourceDocument: 'crop_weather_conditions.json',
    sourceEvidence: 'Drainage management trials in heavy black soils. Saturation duration is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report omits computational numeric saturation duration threshold.',
  },
  {
    ruleId: 'RULE-WEATHER-SOY-01',
    cropId: 'soybean',
    threatId: 'soybean_waterlogging',
    threatName: 'Seedling Mortality under Submergence',
    threatCategory: 'PHYSIOLOGICAL_STRESS',
    applicableStageNames: ['Emergence & Early Vegetative'],
    weatherConditionType: 'SUBMERGENCE',
    weatherConditionDescription: 'waterlogging / submergence',
    geographicApplicability: ['Central Zone', 'Madhya Pradesh', 'Maharashtra'],
    sourceReference: 'ICAR Annual Report 2022-23 p.12',
    sourceDocument: 'crop_weather_conditions.json (Record 5)',
    sourceEvidence: 'Climate Resilient Agriculture / Submergence tolerance evaluation. Inundation duration is null.',
    requiredEvidence: ['PHENOLOGY_STAGE', 'WEATHER_DATA', 'WEATHER_THRESHOLD'],
    isComputable: false,
    uncomputableReason: 'Source report omits computational numeric inundation duration threshold.',
  },
];

/**
 * Returns all rules applicable to a given cropId (e.g. "cotton", "rice", "wheat").
 */
export function getRulesForCrop(cropId: string): RiskRule[] {
  const normCrop = cropId.toLowerCase().trim();
  return VALIDATED_RISK_RULES.filter(
    (r) => r.cropId === normCrop || normCrop.includes(r.cropId)
  );
}
